import { MAX_REFRESH_FAMILIES_PER_USER, RefreshFamilySchema, type IRefreshFamily } from '@bee-epic/shared';

/**
 * Repository for `IRefreshFamily` records. Only this module is allowed to
 * read/write `env.CONTENT_KV` for refresh-token-family data, so the storage
 * layout can be swapped out (e.g. to D1) without rippling through handlers.
 *
 * KV key conventions:
 *   - `refresh:<email-lower>:<familyId>` → JSON IRefreshFamily.
 *     Email-then-familyId so `KV.list({prefix: "refresh:<email>:"})` scans
 *     only that user's families — cheap per-user listing without a secondary
 *     index. Family IDs are opaque random strings (URL-safe) generated by
 *     the auth handler that creates the family.
 *
 * Emails are lowercased at every public-API entry — callers do not need to
 * normalize before calling. `createFamily` additionally lowercases the
 * `email` field on the persisted record so the stored JSON's email matches
 * the key.
 *
 * Refresh rotation + replay detection: each family stores `currentJti`; the
 * refresh handler requires the inbound JWT's `jti` to match. Mismatch =
 * replay = caller deletes the family. Rotation updates `currentJti` and
 * `lastRefreshedAt` but does NOT extend `expiresAt` — only a fresh login
 * mints a new family with a new 30-day window.
 *
 * Per-user cap: at most `MAX_REFRESH_FAMILIES_PER_USER` (10) families per
 * email. `createFamily` evicts the oldest (by `createdAt`) until under cap
 * before writing, so a new login on an 11th device kicks the stalest
 * session. KV is eventually consistent so this is best-effort under
 * concurrent logins, but the platform TTL eventually catches any stragglers.
 *
 * TTL: every `createFamily` and `rotateFamily` write sets KV's
 * `expirationTtl` so the platform auto-evicts the record at `expiresAt` —
 * no sweeper required. The read path still re-checks `expiresAt` against
 * `Date.now()` because clocks and KV eviction lag are both imperfect.
 */

const REFRESH_PREFIX = 'refresh:';

function familyKey(email: string, familyId: string): string {
	return `${REFRESH_PREFIX}${email.toLowerCase()}:${familyId}`;
}

function emailPrefix(email: string): string {
	return `${REFRESH_PREFIX}${email.toLowerCase()}:`;
}

function ttlSecondsFor(expiresAt: number): number {
	// KV rejects values < 60 in production, but a positive integer is the
	// only floor that matters for correctness; callers that pass an
	// already-expired `expiresAt` will get a 1-second record they can still
	// write without throwing, which the read path immediately treats as
	// expired.
	return Math.max(1, Math.ceil((expiresAt - Date.now()) / 1000));
}

/**
 * Load a refresh family by email + familyId. Returns null when the key is
 * missing, the stored JSON is corrupt, the schema doesn't validate, OR the
 * family has expired. Expiry triggers a fire-and-forget delete of the stale
 * record so a clock-skew survivor doesn't linger in storage.
 */
export async function getFamily(env: Env, email: string, familyId: string): Promise<IRefreshFamily | null> {
	const key = familyKey(email, familyId);
	const raw = await env.CONTENT_KV.get(key);
	if (!raw) return null;
	let family: IRefreshFamily;
	try {
		const parsed = RefreshFamilySchema.safeParse(JSON.parse(raw));
		if (!parsed.success) {
			console.warn(`[refreshFamilyRepo] schema-invalid record at ${key}`);
			return null;
		}
		family = parsed.data;
	} catch {
		console.warn(`[refreshFamilyRepo] failed to JSON.parse ${key}`);
		return null;
	}
	if (Date.now() >= family.expiresAt) {
		// Fire-and-forget: caller doesn't care, and KV TTL will catch any
		// straggler eventually. Swallow errors so a transient delete failure
		// doesn't surface as a read failure.
		void env.CONTENT_KV.delete(key).catch(() => undefined);
		return null;
	}
	return family;
}

/**
 * Persist a new refresh family. Lowercases the `email` field before
 * validation so the stored record matches the lowercased key. Before
 * writing, enforces the per-user cap: if `listForEmail` already returns
 * `MAX_REFRESH_FAMILIES_PER_USER` records, the oldest (by `createdAt`) are
 * evicted until under cap. The eviction happens BEFORE the put so the new
 * family is never briefly the 11th; KV is eventually consistent so this is
 * best-effort under concurrent creates. Cap counts only well-formed
 * records; corrupt records are best-effort cleaned by platform TTL.
 */
export async function createFamily(env: Env, family: IRefreshFamily): Promise<void> {
	const normalized: IRefreshFamily = { ...family, email: family.email.toLowerCase() };
	const parsed = RefreshFamilySchema.parse(normalized);
	// Cap-eviction: listForEmail returns oldest-first, so shift() pulls the
	// stalest. Loop because a prior partial-failure could have left the user
	// over cap and we want to recover to under-cap in one call.
	const existing = await listForEmail(env, parsed.email);
	while (existing.length >= MAX_REFRESH_FAMILIES_PER_USER) {
		const victim = existing.shift();
		if (!victim) break;
		await env.CONTENT_KV.delete(familyKey(parsed.email, victim.familyId));
	}
	await env.CONTENT_KV.put(familyKey(parsed.email, parsed.familyId), JSON.stringify(parsed), {
		expirationTtl: ttlSecondsFor(parsed.expiresAt),
	});
}

/**
 * Rotate a refresh family: update `currentJti` and `lastRefreshedAt`,
 * preserving `expiresAt` (only login extends the window). Returns the
 * updated family on success, or null if the family is missing/expired so
 * the caller can issue a 401. The KV `expirationTtl` is clamped from the
 * original (untouched) `expiresAt`.
 */
export async function rotateFamily(env: Env, email: string, familyId: string, newJti: string, now: number): Promise<IRefreshFamily | null> {
	const existing = await getFamily(env, email, familyId);
	if (!existing) return null;
	const updated: IRefreshFamily = {
		...existing,
		currentJti: newJti,
		lastRefreshedAt: now,
	};
	const parsed = RefreshFamilySchema.parse(updated);
	await env.CONTENT_KV.put(familyKey(parsed.email, parsed.familyId), JSON.stringify(parsed), {
		expirationTtl: ttlSecondsFor(parsed.expiresAt),
	});
	return parsed;
}

/**
 * Delete a single refresh family. Idempotent — silently no-ops if the
 * record is absent.
 */
export async function deleteFamily(env: Env, email: string, familyId: string): Promise<void> {
	await env.CONTENT_KV.delete(familyKey(email, familyId));
}

/**
 * Delete every refresh family for an email. Used on `changePassword` (kill
 * all other sessions) and on account-disabled / role-changed. Returns the
 * number of records actually deleted. Walks the per-email prefix with
 * cursor pagination because `KV.list` has no built-in bulk delete.
 */
export async function deleteAllForEmail(env: Env, email: string): Promise<number> {
	const prefix = emailPrefix(email);
	// First pass: collect every key under the prefix. Deleting while we walk
	// the cursor would shift the keyspace under our feet and risk skipping
	// records, so we materialize the hit list first and then delete in a
	// second pass.
	const matches: string[] = [];
	let cursor: string | undefined;
	do {
		const listing = await env.CONTENT_KV.list({ prefix, cursor });
		for (const { name } of listing.keys) {
			matches.push(name);
		}
		cursor = listing.list_complete ? undefined : listing.cursor;
	} while (cursor);
	for (const name of matches) {
		await env.CONTENT_KV.delete(name);
	}
	return matches.length;
}

/**
 * List every refresh family for an email, sorted by `createdAt` ascending
 * (oldest first). Parse failures are skipped — corruption in one family
 * shouldn't crash the cap-eviction path or the Sessions tab — but the
 * stale entries are left for the platform TTL or a future repair to handle.
 * Paginates the prefix scan with a cursor loop.
 */
export async function listForEmail(env: Env, email: string): Promise<IRefreshFamily[]> {
	const prefix = emailPrefix(email);
	const families: IRefreshFamily[] = [];
	let cursor: string | undefined;
	do {
		const listing = await env.CONTENT_KV.list({ prefix, cursor });
		for (const { name } of listing.keys) {
			const raw = await env.CONTENT_KV.get(name);
			if (!raw) continue;
			try {
				const parsed = RefreshFamilySchema.safeParse(JSON.parse(raw));
				if (!parsed.success) {
					console.warn(`[refreshFamilyRepo] schema-invalid record at ${name}`);
					continue;
				}
				families.push(parsed.data);
			} catch {
				console.warn(`[refreshFamilyRepo] failed to JSON.parse ${name}`);
				continue;
			}
		}
		cursor = listing.list_complete ? undefined : listing.cursor;
	} while (cursor);
	families.sort((a, b) => a.createdAt - b.createdAt);
	return families;
}
